### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by flaxues** [SalmonGER/SkinChanger#3]
Hello

I'm using this plugin because of capes to use it on my own skin. But everyone now has the skins you added. For example spongebob is there a way to disable this option so that everyone has their own skin?

**Comment by SalmonGER** [comment]
@flaxues Sorry, please disable JoinSkins in your config file:
https://github.com/SalmonGER/SkinChanger/blob/master/resources/config.yml#L6

**Comment by flaxues** [comment]
I'm so blind

Thanks for the help :)
