### ISSUE TITLE
how to add skin?

### ISSUE THREAD

**Issue by padrone21** [SalmonGER/SkinChanger#4]
how to add skin?

**Comment by KairusDarkSeeker** [comment]
can you elaborate?

**Comment by padrone21** [comment]
so we can add our own skin to wear another player

**Comment by SalmonGER** [comment]
@padrone21 If you're online you can use /changeskin padrone21 [OtherPlayer]

**Comment by padrone21** [comment]
add new skin in plugin, so I can set some of my skin to them

**Comment by KairusDarkSeeker** [comment]
@padrone21 t

**Comment by Aericio** [comment]
Only way (that's easy) is to use that command.

**Comment by SalmonGER** [comment]
@padrone21 I'll add a /addskin command

**Comment by SalmonGER** [comment]
Finished. :)
Please look at the README file for a quick introduction into the /saveskin command @padrone21 !
