### ISSUE TITLE
Great idea, really bad code

### ISSUE THREAD

**Issue by legoboy0215** [SalmonGER/SkinChanger#5]
Bad as in very badly optimized. Seriously, you are lagging the shit out of a server I work for. Can you at least try and optimized?

**Comment by Aericio** [comment]
It does not lag at all.

**Comment by SalmonGER** [comment]
Actually I guess there is a thing I could change

**Comment by legoboy0215** [comment]
Also, str_ireplace is like useless. Better change that to str_replace.

**Comment by SalmonGER** [comment]
@legoboy0215 Well that makes message lines case sensitive, but it shouldn't make much difference so I'm fine with that
