### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by Aericio** [SalmonGER/SkinChanger#8]
`Notice: Undefined index: Keiner in phar:///home/gmplus/Server/plugins/SkinChange                                                                                        r.phar/src/SalmonDE/Skin.php on line 64
`

**Comment by SalmonGER** [comment]
Recreate your messages.ini file and check if this error still occurs on /changecape

**Comment by SalmonGER** [comment]
Recreate your messages.ini file and check if this error still occurs on /changecape

**Comment by Aericio** [comment]
dunno

**Comment by KairusDarkSeeker** [comment]
@SalmonGER just add isset() and the error will go away

**Comment by SalmonGER** [comment]
@KairusDarkSeeker I think that's not necessary since it's just the result of a outdated messages.ini file

**Comment by KairusDarkSeeker** [comment]
@SalmonGER mk
