### ISSUE TITLE
Other players can see the changed skin but the player whose skin is changed sometimes cannot see the skin changed

### ISSUE THREAD

**Issue by Ishannaik** [SalmonGER/SkinChanger#9]
when someone changes my skin it changes for them but it sometimes it doesnt changes for me

**Comment by Aericio** [comment]
If you wait a while, it should change for you too.

**Comment by Ishannaik** [comment]
i tried it but it doesn't work and when player relogs his original skin is back

**Comment by KairusDarkSeeker** [comment]
Its a bug for mcpe and mcwin10 clients, if you want to see the skin change goto your home screen then goback to mcpe if the skin doesn't still change repeat it again

**Comment by Aericio** [comment]
I believe you can enable `JoinSkins: true` in config.yml and it should save the skin, but I am not sure.
NOTE: This does lag the server more though.

**Comment by SalmonGER** [comment]
JoinSkins actually replaces the skin of a player without the bypass perm when he joins

**Comment by SalmonGER** [comment]
@Ishannaik what do you mean by adding more skinpacks?

**Comment by Ishannaik** [comment]
you added skin pack villan i read it in the update notes so i said add more skin packs

**Comment by Aericio** [comment]
There won't be any updates for a week since @SalmonGER is currently away. After a week, there should be new skin packs added ;)

**Comment by SalmonGER** [comment]
@Ishannaik those skinids were added to detect if a player is female
